# Generated by Django 5.2.4 on 2025-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reconciliationlog",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="reconciliationlog",
            name="match_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
