# Generated by Django 5.2.4 on 2025-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0002_invoice_reference_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("unmatched_transactions", "Unmatched Transactions"),
                            ("reconciliation_summary", "Reconciliation Summary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("recipients", models.TextField()),
                ("unmatched_count", models.IntegerField(default=0)),
                ("total_transactions", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
